/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class', // Enable class-based dark mode
  theme: {
    extend: {
      colors: {
        canvas: 'var(--canvas)',
        'canvas-soft': 'var(--canvas-soft)',
        'canvas-deep': 'var(--canvas-deep)',
        'surface-card': 'var(--surface-card)',
        'surface-strong': 'var(--surface-strong)',
        'surface-dark': 'var(--surface-dark)',
        'surface-dark-elevated': 'var(--surface-dark-elevated)',
        primary: 'var(--primary)',
        'primary-active': 'var(--primary-active)',
        hairline: 'var(--hairline)',
        'hairline-soft': 'var(--hairline-soft)',
        'hairline-strong': 'var(--hairline-strong)',
        ink: 'var(--ink)',
        body: 'var(--body)',
        'body-strong': 'var(--body-strong)',
        muted: 'var(--muted)',
        'muted-soft': 'var(--muted-soft)',
        'on-primary': 'var(--on-primary)',
        'on-dark': 'var(--on-dark)',
        'on-dark-soft': 'var(--on-dark-soft)',
        'gradient-mint': 'var(--gradient-mint)',
        'gradient-peach': 'var(--gradient-peach)',
        'gradient-lavender': 'var(--gradient-lavender)',
        'gradient-sky': 'var(--gradient-sky)',
        'gradient-rose': 'var(--gradient-rose)',
        'semantic-success': 'var(--semantic-success)',
        'semantic-error': 'var(--semantic-error)',
      },
      fontFamily: {
        display: ['"EB Garamond"', '"Times New Roman"', 'serif'],
        body: ['Inter', 'sans-serif'],
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        base: '16px',
        md: '20px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '24px',
        pill: '9999px',
        full: '9999px',
      },
      letterSpacing: {
        'display-mega': '-1.92px',
        'display-xl': '-0.96px',
        'display-lg': '-0.36px',
        'display-md': '-0.32px',
        'display-sm': '0px',
        'body-md': '0.16px',
        'body-sm': '0.15px',
        'caption-uppercase': '0.96px',
      },
    },
  },
  plugins: [],
};
